version: "3.9"

services:
  clonebot:
    image: docker.io/xyouxiu6/clonebotv2
    container_name: amgcbot
    environment:
      - CONFIG_FILE_URL=${CONFIG_FILE_URL}
    ports:
      - 8080:8080
    restart: unless-stopped
